<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias {alias} has been deleted' => '',
    'Alias {alias} has been updated' => '',
    'Are you sure you want to delete these ' => '',
    'Are you sure you want to delete these {item}?' => '',
    'City {city} has been deleted' => '',
    'City {city} has been updated' => '',
    'County {county} has been deleted' => '',
    'County {county} has been updated' => '',
    'State {state} has been deleted' => '',
    'State {state} has been updated' => '',
    'Unabled to update {alias}' => '',
    'Unabled to update {city}' => '',
    'Unabled to update {county}' => '',
    'Unabled to update {state}' => '',
    'states' => '',
];
