<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Are comments available on the page?' => '',
    'Cms Pages' => '',
    'Comments available' => '',
    'Content' => '',
    'Create' => '',
    'Create Page' => '',
    'Date Created' => '',
    'Date Updated' => '',
    'File Extension' => '',
    'File Version' => '',
    'Go Back' => '',
    'ID' => '',
    'Markdown Content' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Meta Title' => '',
    'Page has been created.' => '',
    'Page has been deleted.' => '',
    'Page has been updated.' => '',
    'Select' => '',
    'Select Status' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'This one accepts only letters, numbers, dash and slash, i.e. "docs/installation".' => '',
    'Title' => '',
    'Update' => '',
    'Update Page: {0}' => '',
    'Url' => '',
    'View' => '',
    'View Comments' => '',
];
