<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abbr' => '',
    'Active' => '',
    'Add City' => '',
    'Add Zip' => '',
    'Adjective' => '',
    'Alias' => '',
    'Alias ID={id} not found?' => '',
    'Are you sure you want to delete these {item}?' => '',
    'Are you sure you want to delete this item?' => '',
    'Cannabis Breeder' => '',
    'CannabisBreeder' => '',
    'Choose Geo county' => '',
    'Choose city' => '',
    'Choose county' => '',
    'Choose state' => '',
    'Cities' => '',
    'City' => '',
    'City Aliases' => '',
    'City ID' => '',
    'City ID={id} not found?' => '',
    'Counties' => '',
    'Countries' => '',
    'Country' => '',
    'Country Code' => '',
    'County' => '',
    'County ID={id} not found?' => '',
    'Create' => '',
    'Create City' => '',
    'Create County' => '',
    'Create Geo City Alias' => '',
    'Create Geo Country' => '',
    'Create State' => '',
    'Create Zip' => '',
    'Delete' => '',
    'Deleted' => '',
    'Demonym' => '',
    'Geo City Alias' => '',
    'Geo City Aliases' => '',
    'Geo Counties' => '',
    'Geo Countries' => '',
    'Geo Country' => '',
    'Geo Zip' => '',
    'Geography' => '',
    'ID' => '',
    'Inactive' => '',
    'Latitude' => '',
    'Longitude' => '',
    'New Alias' => '',
    'New City' => '',
    'New Country' => '',
    'New County' => '',
    'New State' => '',
    'New Zip' => '',
    'Reset' => '',
    'Search' => '',
    'State' => '',
    'State Code' => '',
    'State ID={id} not found?' => '',
    'States' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'With selected: ' => '',
    'Zip' => '',
    'Zips' => '',
    'aliases' => '',
    'cities' => '',
    'counties' => '',
    'countries' => '',
    'zips' => '',
];
