<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' $' => '@@@@',
    ' S/.' => '',
    ' item(s)' => '',
    'Account' => '',
    'Administration' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to sign out?' => '',
    'Back To Login' => '',
    'Check your email for further instructions.' => '@@@@',
    'Create An Account' => '',
    'Don\'t Have An Account Yet ?' => '',
    'Email' => '',
    'Error occurred while changing password.' => '',
    'Error occurred while deleting user.' => '',
    'Error | Please, you need to Sing In. | Continuar' => '',
    'Error | Sorry, we are unable to reset password for email provided. | Continuar' => '',
    'Excelente | Check your email for further instructions. | Continuar' => '',
    'Excelente | Usuario creado Exitosamente! | Continuar' => '',
    'Forgot your password?' => '',
    'Good Afternoon!' => '',
    'Hecho | El producto fue eliminado del carrito de compras. | Continuar' => '',
    'Incorrect email or password.' => '',
    'Last login' => '',
    'Let\'s make today a great day!' => '',
    'Login' => '',
    'Logout' => '',
    'Password' => '',
    'Password Recovery' => '',
    'Password has been changed.' => '',
    'Password reset for {0}' => '',
    'Please choose your new password:' => '',
    'Please fill in below form to create an account with us' => '',
    'Please fill out the following fields to login:' => '',
    'Please fill out the following fields to signup:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Please fix the following errors:' => '',
    'Please, you need to Sing In.' => '@@@@',
    'Recover Password' => '',
    'Registration time' => '',
    'Remember Me' => '',
    'Reset password' => '',
    'Save' => '',
    'Send' => '',
    'Sign In' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '@@@@',
    'Status' => '',
    'The role "{roleName}" is not found.' => '',
    'The role has been successfully assigned to the user.' => '',
    'The role has been successfully revoked from the user.' => '',
    'This email address has already been taken.' => '',
    'This role already assigned to this user.' => '',
    'This role is not assigned to this user.' => '',
    'This username has already been taken.' => '',
    'User Created Successfully.' => '@@@@',
    'User has been created.' => '',
    'User has been deleted.' => '',
    'User is not found.' => '',
    'User with this email is not found.' => '',
    'Username' => '',
    'Your account has been deactivated, please contact support for details.' => '',
    'Your email' => '',
    'Your password' => '',
    'Your username' => '',
];
