<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this user?' => '',
    'Email' => '',
    'Error occurred while changing password.' => '',
    'Error occurred while deleting user.' => '',
    'Forgot your password?' => '',
    'Incorrect email or password.' => '',
    'Last login' => '',
    'Login' => '',
    'Password' => '',
    'Password has been changed.' => '',
    'Password reset for {0}' => '',
    'Please choose your new password:' => '',
    'Please fill out the following fields to login:' => '',
    'Please fill out the following fields to signup:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Please fix the following errors:' => '',
    'Recover Password' => '',
    'Registration time' => '',
    'Remember Me' => '',
    'Reset password' => '',
    'Save' => '',
    'Send' => '',
    'Signup' => '',
    'Status' => '',
    'The role "{roleName}" is not found.' => '',
    'The role has been successfully assigned to the user.' => '',
    'The role has been successfully revoked from the user.' => '',
    'This email address has already been taken.' => '',
    'This role already assigned to this user.' => '',
    'This role is not assigned to this user.' => '',
    'This username has already been taken.' => '',
    'User has been created.' => '',
    'User has been deleted.' => '',
    'User is not found.' => '',
    'User with this email is not found.' => '',
    'Username' => '',
    'Your account has been deactivated, please contact support for details.' => '',
];
